language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    recipients:
      - dan.kubb@gmail.com
    on_success: never
    on_failure: change
matrix:
  include:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    # yard parser fails
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
