language: ruby
bundler_args: --without yard guard benchmarks --path vendor/bundle --jobs=3 --retry=3
script: "bundle exec rake ci:metrics"
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --2.0"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
